/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class RangeChecker */

#ifndef _Included_RangeChecker
#define _Included_RangeChecker
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     RangeChecker
 * Method:    getAgentsInRange
 * Signature: (Ljava/lang/String;Ljava/util/ArrayList;)Ljava/util/ArrayList;
 */
JNIEXPORT jobject JNICALL Java_RangeChecker_getAgentsInRange
  (JNIEnv *, jobject, jstring, jobject);

#ifdef __cplusplus
}
#endif
#endif
